### ISSUE TITLE
Allow multiple assertions.

### ISSUE THREAD

**Issue by billybonks** [ember-cli/aot-test-generators#11]
ember-cli-stylint shows the errors in tests.

https://github.com/billybonks/ember-cli-stylelint/blob/master/index.js#L49
![image](https://user-images.githubusercontent.com/1640136/36550090-591584e0-182f-11e8-8c67-4dbac90998e6.png)

so does, broccoli-style-lint. i started implementing aot-test-generators. but need the option of adding my own assertions for feature parity.

![image](https://user-images.githubusercontent.com/1640136/36550350-0b234ee2-1830-11e8-8aa0-068e6748506f.png)

Do you have any concerns with  allowing assertionMessage to be an array. if it is a string it will do the current behaviour if it is an array it will add an assertion for each entry.
`test(testName, passed, [assertionMessage])`

cc @Turbo87

**Comment by Turbo87** [comment]
The problem with your proposal is that if a file has multiple problems only one of them will be displayed. I would prefer it if we could build a string that includes all of the issues of the file and include it in a single assertions.

For QUnit having multiple assertions might be fine as it will display all of them, but for chai/mocha this will be a problem.
